# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export MANPAGER="nvim +Man!."
export QT_QPA_PLATFORM=wayland

# Init
if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init --cmd cd bash)"
fi

if command -v fzf &> /dev/null; then
  eval "$(fzf --bash)"
fi

if command -v try &> /dev/null; then
  eval "$(try init ~/Development/tries)"
fi

# Aliases
if command -v eza &> /dev/null; then
  alias ls='eza -lh --group-directories-first --icons=auto'
fi
